import React from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import "../../../styles/loan/customerLoan/LoanDetailCard.css";
import { FaTimes } from "react-icons/fa";

function LoanDetailCard({ loan, onClose }) {
  if (!loan) return null;

  const downloadPDF = () => {
    const doc = new jsPDF();

    // 🧠 Brand Header
    doc.setFontSize(22);
    doc.setTextColor(33, 37, 41);
    doc.text("SmartLend", 105, 20, { align: "center" });

    // 🧾 Subheader
    doc.setFontSize(13);
    doc.setTextColor(80);
    doc.text("Loan Application Summary", 105, 28, { align: "center" });

    const rows = [
      ["Applicant Name", loan.customer?.name || "N/A"],
      ["Email", loan.customer?.email || "N/A"],
      ["Contact", loan.customer?.contactNumber || "N/A"],
      ["City", loan.customer?.city || "N/A"],
      ["Loan Type", loan.loanType?.name || "N/A"],
      ["Amount", `₹ ${Number(loan.amount).toLocaleString("en-IN")}`],
      ["Tenure", `${loan.tenureYears} Years`],
      ["Purpose", loan.purpose || "N/A"],
      ["Employment Info", loan.employmentInfo || "N/A"],
      ["Monthly Income", loan.income || "N/A"],
      ["PAN", loan.pan || "N/A"],
      ["Aadhaar", loan.aadhaar || "N/A"],
      ["Previous Active Loans", loan.previousActiveLoans || 0],
      ["CIBIL Score", loan.cibilScore || "N/A"],
      ["Status", loan.loanStatus || "N/A"],
      [
        "Submitted On",
        loan.submittedAt
          ? new Date(loan.submittedAt).toLocaleString("en-IN")
          : "N/A",
      ],
    ];

    autoTable(doc, {
      startY: 35,
      head: [["Field", "Value"]],
      body: rows,
      theme: "striped",
      headStyles: {
        fillColor: [3, 61, 107],
        textColor: [255, 255, 255],
        fontSize: 12,
        halign: "center",
      },
      styles: {
        cellPadding: 4,
        fontSize: 11, // Increased font size
        valign: "middle",
      },
      columnStyles: {
        0: { fontStyle: 'bold', textColor: 40 },
        1: { textColor: 50 },
      },
    });

    // 📧 Footer with contact info
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      "Generated by SmartLend • Email: SmartLendLms1@gmail.com",
      105,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );

    doc.save(`Loan_Application_${loan.id}.pdf`);
  };

  return (
    <div className="loan-detail-card">
      <button className="close-icon" onClick={onClose}>
        <FaTimes size={18} />
      </button>

      <h3>Loan Application Details</h3>

      <div className="loan-detail-grid">
        <div><strong>Applicant Name:</strong> {loan.customer?.name}</div>
        <div><strong>Email:</strong> {loan.customer?.email}</div>
        <div><strong>Contact No:</strong> {loan.customer?.contactNumber}</div>
        <div><strong>City:</strong> {loan.customer?.city}</div>

        <div><strong>Loan Type:</strong> {loan.loanType?.name}</div>
        <div><strong>Amount:</strong> ₹ {Number(loan.amount).toLocaleString("en-IN")}</div>
        <div><strong>Tenure:</strong> {loan.tenureYears} Years</div>
        <div><strong>Purpose:</strong> {loan.purpose}</div>

        <div><strong>Employment Info:</strong> {loan.employmentInfo}</div>
        <div><strong>Monthly Income:</strong> {loan.income}</div>
        <div><strong>PAN:</strong> {loan.pan}</div>
        <div><strong>Aadhaar:</strong> {loan.aadhaar}</div>

        <div><strong>Previous Active Loans:</strong> {loan.previousActiveLoans}</div>
        <div><strong>CIBIL Score:</strong> {loan.cibilScore}</div>
        <div><strong>Status:</strong> {loan.loanStatus}</div>
        <div><strong>Submitted On:</strong> {new Date(loan.submittedAt).toLocaleString("en-IN")}</div>
      </div>

      <div className="loan-detail-btns">
        <button onClick={downloadPDF}>Download as PDF</button>
      </div>
    </div>
  );
}

export default LoanDetailCard;
